# Use a lightweight Python base image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy application code into the container
COPY main.py .

# Expose the port
EXPOSE 8000

# Run  Python app
CMD ["python", "main.py"]
